import os
f = open('poem.txt', 'w', encoding='utf-8')
f.write('静夜思\n作者：李白\n床前明月光，\n疑是地上霜。\n举头望明月，\n低头思故乡。')
# f.close()
f = open('poem.txt', 'r', encoding='utf-8')
a = f.read()
print(a)
f.seek(0)
lines = f.readlines()
author = lines[1].strip()
print('静夜思的', author)
f.close()

os.rename('poem.txt', 'myfavouritepoem.txt')
f = open('myfavouritepoem.txt', 'a', encoding='utf-8')
f.write('\n春晓\n作者：孟浩然\n春眠不觉晓，\n处处闻啼鸟。\n夜来风雨声，\n花落知多少。')
f.close()
f = open('myfavouritepoem.txt', 'r', encoding='utf-8')
b = f.read()
print(b)
f.close()
